### ISSUE TITLE
Response with body

### ISSUE THREAD

**Issue by g4s8** [artipie/http#29]
Add response with bytes or text body

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/http/issues/29#issuecomment-583363175))

@g4s8 The job [#29](https://github.com/artipie/http/issues/29) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0d499647-c1eb-4177-a5dc-c4d1fbe2c74d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#37](https://github.com/artipie/http/issues/37) is still not solved.

**Comment by g4s8** [comment]
Done in #36

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#144](https://github.com/artipie/http/issues/144) is still not solved; solved: [#37](https://github.com/artipie/http/issues/37).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#165](https://github.com/artipie/http/issues/165) is still not solved; solved: [#144](https://github.com/artipie/http/issues/144), [#37](https://github.com/artipie/http/issues/37).
