### ISSUE TITLE
Simple implementation of HTTP interfaces

### ISSUE THREAD

**Issue by g4s8** [artipie/http#3]
Add simple implementations of request and response interfaces to build MVP Artipie server.

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#3](https://github.com/artipie/http/issues/3) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8e61b688-da85-464b-9cbd-76e1064aa44a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 3 puzzles [#5](https://github.com/artipie/http/issues/5), [#6](https://github.com/artipie/http/issues/6), [#7](https://github.com/artipie/http/issues/7) are still not solved.

**Comment by g4s8** [comment]
Done in #4

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#5](https://github.com/artipie/http/issues/5), [#7](https://github.com/artipie/http/issues/7) are still not solved; solved: [#6](https://github.com/artipie/http/issues/6).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#11](https://github.com/artipie/http/issues/11), [#5](https://github.com/artipie/http/issues/5) are still not solved; solved: [#6](https://github.com/artipie/http/issues/6), [#7](https://github.com/artipie/http/issues/7).

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#5](https://github.com/artipie/http/issues/5) is still not solved; solved: [#11](https://github.com/artipie/http/issues/11), [#6](https://github.com/artipie/http/issues/6), [#7](https://github.com/artipie/http/issues/7).

**Comment by 0pdd** [comment]
@g4s8 all 4 puzzles are solved here: [#11](https://github.com/artipie/http/issues/11), [#5](https://github.com/artipie/http/issues/5), [#6](https://github.com/artipie/http/issues/6), [#7](https://github.com/artipie/http/issues/7).
